### ISSUE TITLE
Using YAML front matter with markdown helper renders first line as code

### ISSUE THREAD

**Issue by DanielaValero** [helpers/helper-markdown#3]
## description
I am running assemble with gulp, and in my settings, no matter what I write in the first line, it will always be interpreted as if I was writing code.

### Expected behaviour
Renders the first line of the content of the markdown as a headline, or whatever syntax was used in there.

### Actual behaviour
It renders the first line of the .md file as a code block
```html
<pre><code>    # In progress
</code></pre>
```

## version 

0.2.1

#### Markdown file
```md
---
title: Roadmap
---

# In progress
```

#### Layout
```hbs
  {{#markdown}}
      {% body %}
  {{/markdown}}
```

**Comment by DanielaValero** [comment]
The issue was that the spaces between the {% body %} tag was telling the parser that it was a code block. Removing the spaces fixed the issue.

Related issue closed also: https://github.com/assemble/assemble/issues/876

**Comment by jonschlinkert** [comment]
glad we got this figured out! 

you could try using [strip-indent](https://www.npmjs.com/package/strip-indent) in a helper. I've done that in the past but can't remember if there were any drawbacks.

```js
var stripIndent = require('strip-indent');
app.helper('stripIndent', function(options) {
  return stripIndent(options.fn(this));
});
```

You might need to play with the context passed to `options.fn()`, but you should be able to use it like this:

```handlebars
{{#markdown}}
{{#stripIndent}}
    {% body %}
{{#stripIndent}}
{{#markdown}}
```

You could also create another "intermediary" layout that only exists for stripping indentation using this helper. just thinking out loud...
