### ISSUE TITLE
Bug when using with `grunt-assemble@0.6.3`

### ISSUE THREAD

**Issue by lukebussey** [helpers/helper-markdown#4]
@doowb asked me to open an issue here for this bug: https://github.com/assemble/grunt-assemble/issues/61

**Comment by doowb** [comment]
Thanks, I was about to ask you to try something, but it looks like this PR #2 might fix this bug.

**Comment by doowb** [comment]
@lukebussey this was published as a patch so just reinstall your node modules and let us know if that works now.

**Comment by lukebussey** [comment]
Works great! Thanks for the quick resolution and keep up the great work on assemble!

**Comment by doowb** [comment]
Awesome, glad it worked :)
