### ISSUE TITLE
Can't get to work with content from expression

### ISSUE THREAD

**Issue by timdiacon** [helpers/helper-markdown#5]
I want to pass content from a variable into the markdown helper, something like this but it doesn't work?

`{{#markdown}}{{myContent}}{{/markdown}}`

I'm guessing I need some other kind of syntax?

**Comment by doowb** [comment]
That should work. Can you provide a simplified gist or repository that reproduces the issue you're having?

**Comment by timdiacon** [comment]
I think this was me being dumb and not installing the helper correctly, working perfectly now! I love this Git Repo thanks so much 🙏
