### ISSUE TITLE
First line always renders as <pre><code>

### ISSUE THREAD

**Issue by stefany-newman** [helpers/helper-markdown#6]
If the first line in my markdown doesn't start with a `\n` , then the  `{{#markdown}} {{/markdown}}` tags renders it as `<pre><code>`

**Example**

This text `### Marlene Dietrich ` gets rendered as `<pre><code>Marlene Dietrich</code></pre>` instead of `<h3>Marlene Dietrich</h3>`

However if the text starts with a _\n_ it will render with the h3 tags. 
Same with pics, paragraphs, etc.
Please help.

**Comment by doowb** [comment]
Hi @Stefany93, can you show an example of the templates that you're using? It might just have something to do with other whitespace that's causing the text inside of the `{{#markdown}} {{/markdown}}` body to be indented in a way that it's being rendered as a code block.

**Comment by stefany-newman** [comment]
Thanks for replaying doowb! Here is template I am using (assemble + .hbs files)


`{{#markdown}}  
                   {{content.body}}   
                {{/markdown}}  `


content.body is the JSON that has the text with the markdown. Loaded via assemble `options.pages`

**Comment by doowb** [comment]
Is that used in a partial? Do you have an example repository that I could look at?

Also, which version of `assemble` are you using?

**Comment by stefany-newman** [comment]
It is used in a layout.hbs file

 assemble@0.24.3

Don't have repo, sorry. 

Basically the JSON is fetched from Storyblok which contains MD, then downloaded a JSON file, loaded into Assemble, parsed with the Markdown plugin. 

The first line is always `<code>` :/

**Comment by stefany-newman** [comment]
![image](https://user-images.githubusercontent.com/2403939/43283561-d964b7c4-90de-11e8-8231-f8d22e81f054.png)

I even added custom header and it was parsed as `<code>` :/

**Comment by stefany-newman** [comment]
^^ Thank you for your help doowb, I fixed it:

Apperantly the indent space to indent the block was generating the weird tags.

So I changed the indentation to this:
![image](https://user-images.githubusercontent.com/2403939/43287332-64bc63ac-90ea-11e8-9d47-15081a7e4bce.png)
 
From this:

![image](https://user-images.githubusercontent.com/2403939/43287357-7258cbf4-90ea-11e8-91a6-d4d158fff173.png)

And it worked!

**Comment by doowb** [comment]
@Stefany93 I'm glad you figure it out. I was thinking that it had something to do with the indentation since code blocks can either be specified with 3 backticks or indented 4 spaces.

**Comment by stefany-newman** [comment]
yes apperantly, the block treats everything inside it as markdown or something... thank you so much for helping!

**Comment by acespace90** [comment]
Hi guys, I'm in the exact situation of @Stefany93

JSON is fetched from Strapi which contains MD, then downloaded a JSON file, loaded into HBS, parsed with the Markdown plugin.

But if I do 
```
<p class="text-secondary">
  {{#markdown}}{{ bodyText }}{{/markdown}}
</p>
```
nothing appears on screen.

But if I write
```
{{#markdown}}**lorem ipsum**{{/markdown}}
```
then bold text is applied on lorem ipsum.

Can you help me please?
Thanks

**Comment by doowb** [comment]
> nothing appears on screen.

This tells me that `{{ bodyText }}` is empty, which means that you could be trying to access a variable at a different "depth"...

If you do:

```hbs
<p class="text-secondary">
  {{ bodyText }}
</p>
```

And there is content between the `<p>` tags, then try:

```hbs
<p class="text-secondary">
  {{#markdown}}{{ ../bodyText }}{{/markdown}}
</p>
```

This will tell handlebars to "look up" 1 level of "depth" to find the variable `bodyText`.

If that doesn't work, then I'll need more information about your configuration to try to help.

**Comment by acespace90** [comment]
@doowb it works! Thanks.

But ehy, I'm not understanding why. I mean, if I write
```
<p class="text-secondary">
  {{ bodyText }}
</p>
```

The text is printed on page, so this explains that `bodyText` is not empty.

Why do I have to access the variable at different depth doing like you showed to me?
